apiVersion: v1
kind: Template
labels:
  app: oauth-interface-client-groups
  template: oauth-interface-client-groups
metadata:
  annotations:
    description: Template to create project to use to interface with backend services.
    iconClass: icon-nodejs
    openshift.io/display-name: OpenShift Oauth Interface - Client Groups
    openshift.io/documentation-url: https://github.com/devcomb/nginx-cfg
    openshift.io/long-description: This template defines resources needed to interface
      with server already running in another namespace. 
    openshift.io/provider-display-name: ''
    openshift.io/support-url: ''
    tags: nodejs,nginx,oauth,proxy
    template.openshift.io/bindable: 'false'
  name: oauth-interface-client
objects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: group_reader_rolebinding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: group-reader
  subjects:
    - kind: ServiceAccount
      name: default
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: developer_rolebinding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: developer
  subjects:
    - kind: User
      name: ${DEV_USERNAMES}
    - kind: Group
      name: developer
parameters:
  - description: Usernames added to developer group
    displayName: dev_usernames
    name: DEV_USERNAMES
    required: true
    value: ''